### ISSUE TITLE
ViewContainerRef

### ISSUE THREAD

**Issue by tkoseoglu** [PointInside/ng2-toastr#123]
Hi,
I've upgraded to 1.3.6 and angular is 2.4.3
I am getting an error that looks like this

Uncaught (in promise): Error: Please set root ViewContainerRef using setRootViewContainerRef(vRef: ViewContainerRef) method.
Error: Please set root ViewContainerRef using setRootViewContainerRef(vRef: ViewContainerRef) method.

Thanks.
--tolga

**Comment by derekshi** [comment]
In your root component do something like this:
```
constructor(private toastr: ToastsManager, vRef: ViewContainerRef) {
    this.toastr.setRootViewContainerRef(vRef);
  }
```

**Comment by HydTechie** [comment]
This fix is working! but I got to add in every component wherever toastr is used. when I added in AppComponent (boot strapped) constructor, It was resulting error, did I miss any. 

Another issue, when I added min.js and min.css from node_modules, it worked, but not worked with usual angular-cli build... any clues? thanks!

**Comment by steveperx** [comment]
You don't need to add the JS to angular-cli.

If you're getting the error "Uncaught ReferenceError: System is not defined", it's because you've added the JS file to your "scripts" section in angular-cli.json.  Take it out, and just import ToastModule in your module file.

From the front page of the Github readme:
> NOTE: If you are using angular-cli you do not need to include 'node_modules/ng2-toastr/bundles/ng2-toastr.min.js', since adding 'import {ToastModule} from 'ng2-toastr/ng2-toastr';' to your module file (below) will allow it to be autoloaded.

**Comment by ssljivic** [comment]
@derekshi it really is annoying to have the following code in each component where toast is used:

```
constructor(private toastr: ToastsManager, vRef: ViewContainerRef) {
    this.toastr.setRootViewContainerRef(vRef);
  }
```

Is there a way to have that configured in one place only?


Thanks

**Comment by derekshi** [comment]
You only need to put it into root component. Other component will automatically inherit it.

**Comment by santanu-biswas** [comment]
I have put it in root component (AppComponent), but **it does not get inherited**.

**Comment by santanu-biswas** [comment]
After doing some research, I figured out that this problem happens in lazy loaded modules. The reason for this behaviour is that in `toast.module.ts` the service `ToastManager` has been added to the `providers` in the module metadata.

```
@NgModule({
    imports: [CommonModule],
    declarations: [ToastContainer],
    exports: [ToastContainer],
    providers: [ToastsManager],      // <===
    entryComponents: [ToastContainer]
})
```

This, in my opinion, is the source of the problem, because, it results in a new instance of `ToastsManager` in every new module, and hence the `_rootViewContainerRef` has to be set in every module.

**The correct way should be to add it to the static `forRoot` method so that `ToastsManager` becomes a singleton.**

**Comment by santanu-biswas** [comment]
In addition to the above, in the newer Angular versions the [following line](https://github.com/PointInside/ng2-toastr/blob/master/src/toast-manager.ts#L42) in `toast-manager.ts` will not work:

`this._rootViewContainerRef = this.appRef['_rootComponents'][0]['_hostElement'].vcRef;`

There is no property named `_hostElement` in the new versions. Also, it is not a good idea to depend on private variables as there is no assurance of these remaining the same in new versions.

**Comment by derekshi** [comment]
@santanu-biswas, thanks for pointing out the ToastsManager. The new version v1.3.7 has fixed the issue.

**Comment by santanu-biswas** [comment]
That was really quick!
I downloaded the latest version (1.3.7) and tested it on three different applications including lazy-loaded modules. The problem is now resolved. You can close this issue.

**Comment by mich356c** [comment]
I am still getting the error mentioned in the first post.

**app.module.ts**
```
import { ToastModule } from 'ng2-toastr/ng2-toastr';

@NgModule({
    declarations: [...],
    imports: [
        ToastModule.forRoot({
            showCloseButton: true,
            positionClass: "toast-bottom-right",
            animate: "flyRight"
        }),
        ...
    ],
    ...
})
```

**app.component.ts**
```
import { ToastsManager } from 'ng2-toastr/ng2-toastr';

...

    constructor(
        ...
        private toastr: ToastsManager
    ) {
        this.toastr.error('This is not good!', 'Oops!').then(
            yay => {
                console.log(yay);
            },
            nay => {
                console.log(nay);
            }
        );
    }
```

**Comment by sivanandanr** [comment]
Im using Angular 2.4.1 and Router 3.4.1. Toaster 1.3.7 But still im getting error
 Uncaught (in promise): Error: Please set root ViewContainerRef using setRootViewContainerRef(vRef:
I have created shared services for toaster.
import {Injectable, ApplicationRef, ComponentFactoryResolver} from '@angular/core';
import {ToastsManager, Toast, ToastOptions} from 'ng2-toastr/ng2-toastr';
import { Component, ViewContainerRef ,OnInit} from '@angular/core';
import Globals = require("../../shared/globals");

@Injectable()
export class NotificationService {
    constructor(private toastr: ToastsManager, private appl: ApplicationRef, private componentFactoryResolver: ComponentFactoryResolver,viewContainerRef: ViewContainerRef) {
        this.toastr.setRootViewContainerRef(viewContainerRef);
    }

    showWarning(message: string, title: string) {
        let options = new ToastOptions({
            positionClass: 'toast-center-center',
            showCloseButton: true,
            dismiss: 'click'
        });

        let toastManager: ToastsManager = new ToastsManager(this.componentFactoryResolver, this.appl, options);
        toastManager.warning(message, title, options);
    }

    showError(message: string, title: string) {
        let options = new ToastOptions({
            positionClass: 'toast-center-center',
            showCloseButton: true,
            dismiss: 'click'
        });

        let toastManager: ToastsManager = new ToastsManager(this.componentFactoryResolver, this.appl, options);
        toastManager.error(message, title, options);
    }

    showSuccess(message: string, title: string) {
        let options = new ToastOptions({
            positionClass: 'toast-top-right',
            animate: 'flyRight',
            dismiss: 'click',
            toastLife:8000
        });

        let toastManager: ToastsManager = new ToastsManager(this.componentFactoryResolver, this.appl, options);
        toastManager.success(message, title, { toastLife: 5000, dismiss: 'auto', positionClass: 'toast-top-right', animate: 'flyRight' });
    }

    showInfo(message: string, title: string) {
        let options = new ToastOptions({
            positionClass: 'toast-top-right',
            animate: 'flyRight',
            dismiss: 'click',
            toastLife: 8000
        });

        let toastManager: ToastsManager = new ToastsManager(this.componentFactoryResolver, this.appl, options);
        toastManager.info(message, title, options);

    }

    clearAllToasts() {
        this.toastr.clearAllToasts();
    }
}

SharedModule.ts

import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { RolesPermissionsService } from './services/rolespermissions.service';
import { WritePermissionDirective } from '../shared/directives/writepermission.directive';
import { ReadPermissionDirective } from '../shared/directives/readpermission.directive';
import {AuditReasonPopupDirective} from "../shared/directives/auditreasonpopup.directive";
@NgModule({
    imports: [CommonModule, RouterModule],
    declarations: [WritePermissionDirective, ReadPermissionDirective, AuditReasonPopupDirective],
    exports: [CommonModule, FormsModule, RouterModule, WritePermissionDirective, ReadPermissionDirective, AuditReasonPopupDirective]
})

export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [],
        };
    }
}

Getting error How to resolve it.

**Comment by Darshana1** [comment]
I am using ng-x toastr. It is giving me error 
ERROR Error: Uncaught (in promise): TypeError: this.toastr.setRootViewContainerRef is not a function
TypeError: this.toastr.setRootViewContainerRef is not a function
    at new HomeComponent (home.component.ts:25)
    at createClass (core.js:9096)
    at createDirectiveInstance (core.js:8971)
    at createViewNodes (core.js:10191)
    at createRootView (core.js:10105)
    at callWithDebugContext (core.js:11136)
    at Object.debugCreateRootView [as createRootView] (core.js:10623)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:8451)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:3265)
    at ViewContainerRef_.push../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createComponent (core.js:8561)
    at new HomeComponent (home.component.ts:25)
    at createClass (core.js:9096)
    at createDirectiveInstance (core.js:8971)
    at createViewNodes (core.js:10191)
    at createRootView (core.js:10105)
    at callWithDebugContext (core.js:11136)
    at Object.debugCreateRootView [as createRootView] (core.js:10623)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:8451)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:3265)
    at ViewContainerRef_.push../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createComponent (core.js:8561)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3751)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)

How to resolve this. My angular version is 6
