### ISSUE TITLE
ng2-toastr No longer works with Angular 2.2.0-rc.0

### ISSUE THREAD

**Issue by Codermar** [PointInside/ng2-toastr#80]
I just updated Angular 2.2.0-rc.0 and ng2-toastr 1.3.0 No longer works. No errors.

**Comment by derekshi** [comment]
I did some testing and I believe it's an angular bug. The change detection didn't kick in once a toaster is added to container. Once I add `changeDetectorRef.detectChanges()`, the toasts showed up. Let's wait for angular team to fix that.

**Comment by Codermar** [comment]
Agreed. Will wait for the angular fix.

**Comment by luigidallavalle** [comment]
Looks like it's a won't fix due to missing repro.

**Comment by bjaminp** [comment]
I just tested this with 2.2.0 and I'm getting the following error: 

Error: Uncaught (in promise): TypeError: Cannot read property 'vcRef' of undefined
TypeError: Cannot read property 'vcRef' of undefined
    at toast-manager.js:29

**Comment by Codermar** [comment]
Same here...

**Comment by patrickracicot** [comment]
#84 related

**Comment by owndann** [comment]
any updates?

**Comment by derekshi** [comment]
We are still looking for an element solution as version 2.2 breaks the hack to get `ViewContainerRef` of the angular app. For time being, please lock down angular version to 2.1.x. It should solve your problem.

**Comment by joshterrill** [comment]
Is there a temporary work around people who are on 2.2 can use? Is there a snippet of code that exists somewhere we can either pull into our app, or modify your library with to get it to work?

**Comment by derekshi** [comment]
@joshterrill 
I had a temporary solution for Angular 2.2.0.  Please use ng2-toastr v1.3.1. In your root component of your app, do this:
```
   // AppComponent.ts (Root component of your app)

    constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
        this.toastr.setRootViewContainerRef(vRef);
    }
```

**Comment by derekshi** [comment]
The bug in 2.2.0-rc.0 seems got fixed in 2.2.0 release.

**Comment by StevenLiekens** [comment]
Uh, no. This still occurs in my app after updating my dependencies.
Angular 2.2.3
ng2-toastr 1.3.2

```js
zone.js:388 Unhandled Promise rejection: Cannot read property 'vcRef' of undefined ; Zone: angular ; Task: HTMLAnchorElement.addEventListener:click ; Value: TypeError: Cannot read property 'vcRef' of undefined(…) TypeError: Cannot read property 'vcRef' of undefined
    at http://localhost:4200/main.bundle.js:59837:101
    at new ZoneAwarePromise (http://localhost:4200/main.bundle.js:104479:29)
    at ToastsManager.show (http://localhost:4200/main.bundle.js:59828:16)
    at ToastsManager.warning (http://localhost:4200/main.bundle.js:59931:21)
    at LinesComponent.saveChanges (http://localhost:4200/main.bundle.js:55238:21)
    at CompiledTemplate.proxyViewClass.View_LinesComponent0.handleEvent_6 (/AppModule/LinesComponent/component.ngfactory.js:272:34)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:4200/main.bundle.js:71815:37)
    at HTMLAnchorElement.<anonymous> (http://localhost:4200/main.bundle.js:34537:36)
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:104226:35)
    at Object.onInvokeTask (http://localhost:4200/main.bundle.js:32608:37)
```

**Comment by joshterrill** [comment]
@StevenLiekens have you tried doing what I suggested above?

```
// AppComponent.ts (Root component of your app)

    constructor(public toastr: ToastsManager, vRef: ViewContainerRef) {
        this.toastr.setRootViewContainerRef(vRef);
    }
```

**Comment by StevenLiekens** [comment]
@joshterrill I just tried it and that fixes it. Thanks.

**Comment by Verurteilt** [comment]
Any update on this thread? due to the fact that it affects the ability to launch a toastr from anywhere inside your application.

**Comment by dejan-mladenovski** [comment]
Installed version 1.4.1 with Angular 2.2.1 and still not fixed.  I also need it to work from a service.
